<?php

namespace App\Models;

use App\Enum\CurrentPosition;
use App\Enum\VisitAction;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * One immutable gate transition. Visit state is derived from these rows: the
 * visit_states view that backs Visit picks the latest event per visit.
 *
 * Read-only here. The table is append-only and written exclusively by the Go
 * API; nothing in Laravel should save() or delete() this model.
 *
 * Two columns are nullable for historical reasons: staff_id is null on every
 * row backfilled from the pre-event-log schema (the operator was never
 * recorded), and gate_id is null on the backfilled intermediate transitions,
 * whose real gate was never stored.
 *
 * @property string $id
 * @property string $visit_id
 * @property string|null $staff_id
 * @property int|null $gate_id
 * @property VisitAction $action
 * @property CurrentPosition $current_position
 * @property Carbon|null $created_at
 * @property-read Gate|null $gate
 * @property-read Staff|null $staff
 *
 * @method static \Illuminate\Database\Eloquent\Builder<static>|VisitEvent newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|VisitEvent newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|VisitEvent query()
 *
 * @mixin \Eloquent
 */
class VisitEvent extends Model
{
    /**
     * The primary key is a uuidv7 generated by Postgres on insert, so it is
     * neither auto-incrementing nor client-generated.
     */
    protected $keyType = 'string';

    public $incrementing = false;

    /**
     * The table has created_at but no updated_at, and Laravel never writes here.
     */
    public $timestamps = false;

    /**
     * Both relations are rendered for every row of the visit event log, so
     * eager loading them keeps that list at three queries instead of 2n + 1.
     *
     * @var list<string>
     */
    protected $with = ['gate', 'staff'];

    protected function casts(): array
    {
        return [
            'action' => VisitAction::class,
            'current_position' => CurrentPosition::class,
            'created_at' => 'datetime',
        ];
    }

    public function gate(): BelongsTo
    {
        return $this->belongsTo(Gate::class);
    }

    public function staff(): BelongsTo
    {
        return $this->belongsTo(Staff::class);
    }
}
