"""Spatial template constants for ID-card field positions.

Auto-generated by eval/calibrate_template.py. Do not hand-edit;
re-run the calibration script when the eval set grows materially.

Offsets are normalized to the type's reference-anchor baseline:
y_offset = (item.center_y - top_anchor.center_y) / baseline
x_offset = (item.left      - top_anchor.left)     / baseline
where baseline = bottom_anchor.center_y - top_anchor.center_y.
"""
from __future__ import annotations

KTP_REFERENCE_ANCHORS = (
    'NIK',
    'Berlaku Hingga',
)

KTP_ANCHOR_PRIORITY = [
    'NIK',
    'Berlaku Hingga',
    'Nama',
    'Pekerjaan',
    'Kewarganegaraan',
    'Status Perkawinan',
    'Kecamatan',
    'Kel/Desa',
    'RT/RW',
    'Agama',
    'Alamat',
    'Tempat/Tgl Lahir',
    'Jenis kelamin',
    'Gol. Darah',
]

KTP_ANCHOR_OFFSETS: dict[str, dict] = {
    'NIK': {
        "y_offset": 0.0,
        "x_offset": 0.0,
        "samples": 39,
    },
    'Berlaku Hingga': {
        "y_offset": 1.0,
        "x_offset": -0.0167,
        "samples": 39,
    },
    'Nama': {
        "y_offset": 0.1383,
        "x_offset": 0.0,
        "samples": 38,
    },
    'Pekerjaan': {
        "y_offset": 0.8522,
        "x_offset": -0.0166,
        "samples": 38,
    },
    'Kewarganegaraan': {
        "y_offset": 0.925,
        "x_offset": -0.0149,
        "samples": 38,
    },
    'Status Perkawinan': {
        "y_offset": 0.7785,
        "x_offset": -0.0124,
        "samples": 38,
    },
    'Kecamatan': {
        "y_offset": 0.6357,
        "x_offset": 0.1467,
        "samples": 38,
    },
    'Kel/Desa': {
        "y_offset": 0.5631,
        "x_offset": 0.1459,
        "samples": 38,
    },
    'RT/RW': {
        "y_offset": 0.4909,
        "x_offset": 0.1498,
        "samples": 38,
    },
    'Agama': {
        "y_offset": 0.7101,
        "x_offset": -0.0082,
        "samples": 38,
    },
    'Alamat': {
        "y_offset": 0.3533,
        "x_offset": -0.004,
        "samples": 38,
    },
    'Tempat/Tgl Lahir': {
        "y_offset": 0.2115,
        "x_offset": 0.004,
        "samples": 38,
    },
    'Jenis kelamin': {
        "y_offset": 0.2827,
        "x_offset": 0.0,
        "samples": 38,
    },
    'Gol. Darah': {
        "y_offset": 0.2908,
        "x_offset": 1.1976,
        "samples": 39,
    },
}

KTP_FIELDS: dict[str, dict] = {
    'nik': {
        "y_offset": 0.0041,
        "x_offset": 0.5494,
        "multi_line": False,
        "validator": 'nik',
        "splits_into": None,
        "samples": 39,
    },
    'nama': {
        "y_offset": 0.1415,
        "x_offset": 0.5508,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 39,
    },
    'tempat_tgl': {
        "y_offset": 0.2144,
        "x_offset": 0.5451,
        "multi_line": False,
        "validator": 'tempat_tgl',
        "splits_into": ['tempat_lahir', 'tanggal_lahir'],
        "samples": 37,
    },
    'jenis_kelamin': {
        "y_offset": 0.2825,
        "x_offset": 0.5496,
        "multi_line": False,
        "validator": 'sex',
        "splits_into": None,
        "samples": 37,
    },
    'golongan_darah': {
        "y_offset": 0.2885,
        "x_offset": 1.6087,
        "multi_line": False,
        "validator": 'blood',
        "splits_into": None,
        "samples": 11,
    },
    'alamat': {
        "y_offset": 0.357,
        "x_offset": 0.5494,
        "multi_line": True,
        "validator": 'free',
        "splits_into": None,
        "samples": 37,
    },
    'rt_rw': {
        "y_offset": 0.4912,
        "x_offset": 0.5501,
        "multi_line": False,
        "validator": 'rt_rw',
        "splits_into": ['rt', 'rw'],
        "samples": 39,
    },
    'kelurahan': {
        "y_offset": 0.562,
        "x_offset": 0.5494,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 39,
    },
    'kecamatan': {
        "y_offset": 0.612,
        "x_offset": 0.5472,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 38,
    },
    'agama': {
        "y_offset": 0.7029,
        "x_offset": 0.5387,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 36,
    },
    'status_perkawinan': {
        "y_offset": 0.7785,
        "x_offset": 0.561,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 38,
    },
    'pekerjaan': {
        "y_offset": 0.849,
        "x_offset": 0.532,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 39,
    },
    'kewarganegaraan': {
        "y_offset": 0.925,
        "x_offset": 0.5315,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 38,
    },
    'berlaku_hingga': {
        "y_offset": 0.9979,
        "x_offset": 0.5118,
        "multi_line": False,
        "validator": 'berlaku_hingga',
        "splits_into": None,
        "samples": 37,
    },
}

SIM_MODERN_REFERENCE_ANCHORS = (
    'Nama/Name',
    'Diterbitkan Oleh/Issued By',
)

SIM_MODERN_ANCHOR_PRIORITY = [
    'Nama/Name',
    'Diterbitkan Oleh/Issued By',
    'Tempat, Tgl Lahir/Place',
    'Alamat/Address',
    'Pekerjaan/Occupation',
    'Gol Darah/Blood type',
    'Jenis Kelamin/Sex',
]

SIM_MODERN_ANCHOR_OFFSETS: dict[str, dict] = {
    'Nama/Name': {
        "y_offset": 0.0,
        "x_offset": 0.0,
        "samples": 37,
    },
    'Diterbitkan Oleh/Issued By': {
        "y_offset": 1.0,
        "x_offset": 0.0,
        "samples": 37,
    },
    'Tempat, Tgl Lahir/Place': {
        "y_offset": 0.1689,
        "x_offset": 0.0045,
        "samples": 37,
    },
    'Alamat/Address': {
        "y_offset": 0.5057,
        "x_offset": 0.0091,
        "samples": 37,
    },
    'Pekerjaan/Occupation': {
        "y_offset": 0.8299,
        "x_offset": 0.0,
        "samples": 34,
    },
    'Gol Darah/Blood type': {
        "y_offset": 0.3378,
        "x_offset": 0.0045,
        "samples": 37,
    },
    'Jenis Kelamin/Sex': {
        "y_offset": 0.3378,
        "x_offset": 0.7937,
        "samples": 37,
    },
}

SIM_MODERN_FIELDS: dict[str, dict] = {
    'nama': {
        "y_offset": 0.0769,
        "x_offset": 0.0,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 37,
    },
    'tempat_tgl': {
        "y_offset": 0.2465,
        "x_offset": 0.0,
        "multi_line": False,
        "validator": 'tempat_tgl',
        "splits_into": ['tempat_lahir', 'tanggal_lahir'],
        "samples": 37,
    },
    'golongan_darah': {
        "y_offset": 0.4165,
        "x_offset": 0.0045,
        "multi_line": False,
        "validator": 'blood',
        "splits_into": None,
        "samples": 15,
    },
    'jenis_kelamin': {
        "y_offset": 0.4127,
        "x_offset": 0.7937,
        "multi_line": False,
        "validator": 'sex',
        "splits_into": None,
        "samples": 37,
    },
    'alamat': {
        "y_offset": 0.5757,
        "x_offset": 0.0,
        "multi_line": True,
        "validator": 'free',
        "splits_into": None,
        "samples": 35,
    },
    'pekerjaan': {
        "y_offset": 0.9054,
        "x_offset": -0.0045,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 37,
    },
    'tempat_pembuatan': {
        "y_offset": 1.0766,
        "x_offset": -0.009,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 37,
    },
}

SIM_SIX_LINE_REFERENCE_ANCHORS = (
    '2.',
    '6.',
)

SIM_SIX_LINE_ANCHOR_PRIORITY = [
    '2.',
    '6.',
    '5.',
    '3.',
    '4.',
    '1.',
]

SIM_SIX_LINE_ANCHOR_OFFSETS: dict[str, dict] = {
    '2.': {
        "y_offset": 0.0,
        "x_offset": 0.0,
        "samples": 32,
    },
    '6.': {
        "y_offset": 1.0,
        "x_offset": -0.0105,
        "samples": 32,
    },
    '5.': {
        "y_offset": 0.8269,
        "x_offset": -0.0071,
        "samples": 29,
    },
    '3.': {
        "y_offset": 0.1719,
        "x_offset": 0.0,
        "samples": 30,
    },
    '4.': {
        "y_offset": 0.3426,
        "x_offset": 0.0034,
        "samples": 28,
    },
    '1.': {
        "y_offset": -0.1637,
        "x_offset": 0.0,
        "samples": 16,
    },
}

SIM_SIX_LINE_FIELDS: dict[str, dict] = {
    'nama': {
        "y_offset": -0.1623,
        "x_offset": 0.1514,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 32,
    },
    'tempat_tgl': {
        "y_offset": 0.0,
        "x_offset": 0.1736,
        "multi_line": False,
        "validator": 'tempat_tgl',
        "splits_into": ['tempat_lahir', 'tanggal_lahir'],
        "samples": 32,
    },
    'gol_sex': {
        "y_offset": 0.1713,
        "x_offset": 0.1812,
        "multi_line": False,
        "validator": 'free',
        "splits_into": ['golongan_darah', 'jenis_kelamin'],
        "samples": 31,
    },
    'alamat': {
        "y_offset": 0.3427,
        "x_offset": 0.1841,
        "multi_line": True,
        "validator": 'free',
        "splits_into": None,
        "samples": 32,
    },
    'pekerjaan': {
        "y_offset": 0.8217,
        "x_offset": 0.1748,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 32,
    },
    'tempat_pembuatan': {
        "y_offset": 0.9983,
        "x_offset": 0.1716,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 32,
    },
}

SIM_OLD_REFERENCE_ANCHORS = (
    'Nama',
    'Berlaku s/d',
)

SIM_OLD_ANCHOR_PRIORITY = [
    'Nama',
    'Berlaku s/d',
    'Alamat',
    'Tempat &',
    'Tgl.Lahir',
    'No. SIM',
    'Pekerjaan',
]

SIM_OLD_ANCHOR_OFFSETS: dict[str, dict] = {
    'Nama': {
        "y_offset": 0.0,
        "x_offset": 0.0,
        "samples": 12,
    },
    'Berlaku s/d': {
        "y_offset": 1.0,
        "x_offset": 0.8841,
        "samples": 12,
    },
    'Alamat': {
        "y_offset": 0.1228,
        "x_offset": 0.3055,
        "samples": 12,
    },
    'Tempat &': {
        "y_offset": 0.4485,
        "x_offset": 0.8806,
        "samples": 12,
    },
    'Tgl.Lahir': {
        "y_offset": 0.5611,
        "x_offset": 0.8808,
        "samples": 12,
    },
    'No. SIM': {
        "y_offset": 0.8883,
        "x_offset": 0.8808,
        "samples": 12,
    },
    'Pekerjaan': {
        "y_offset": 0.7778,
        "x_offset": 0.9247,
        "samples": 11,
    },
}

SIM_OLD_FIELDS: dict[str, dict] = {
    'nama': {
        "y_offset": 0.0,
        "x_offset": 0.4246,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 12,
    },
    'alamat': {
        "y_offset": 0.1254,
        "x_offset": 0.9032,
        "multi_line": True,
        "validator": 'free',
        "splits_into": None,
        "samples": 11,
    },
    'tempat_lahir': {
        "y_offset": 0.4429,
        "x_offset": 1.6113,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 10,
    },
    'tanggal_lahir': {
        "y_offset": 0.5576,
        "x_offset": 1.5986,
        "multi_line": False,
        "validator": 'date',
        "splits_into": None,
        "samples": 12,
    },
    'pekerjaan': {
        "y_offset": 0.7749,
        "x_offset": 1.6632,
        "multi_line": False,
        "validator": 'free',
        "splits_into": None,
        "samples": 10,
    },
    'nomor_sim': {
        "y_offset": 0.8942,
        "x_offset": 1.6638,
        "multi_line": False,
        "validator": 'nik',
        "splits_into": None,
        "samples": 12,
    },
    'tanggal_berlaku': {
        "y_offset": 1.0,
        "x_offset": 1.6325,
        "multi_line": False,
        "validator": 'date',
        "splits_into": None,
        "samples": 12,
    },
}
