// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/hansenhalim/dgb/api/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClock creates a new instance of MockClock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClock {
	mock := &MockClock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClock is an autogenerated mock type for the Clock type
type MockClock struct {
	mock.Mock
}

type MockClock_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClock) EXPECT() *MockClock_Expecter {
	return &MockClock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type MockClock
func (_mock *MockClock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockClock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockClock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockClock_Expecter) Now() *MockClock_Now_Call {
	return &MockClock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockClock_Now_Call) Run(run func()) *MockClock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClock_Now_Call) Return(time1 time.Time) *MockClock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockClock_Now_Call) RunAndReturn(run func() time.Time) *MockClock_Now_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDigester creates a new instance of MockDigester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDigester(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDigester {
	mock := &MockDigester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDigester is an autogenerated mock type for the Digester type
type MockDigester struct {
	mock.Mock
}

type MockDigester_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDigester) EXPECT() *MockDigester_Expecter {
	return &MockDigester_Expecter{mock: &_m.Mock}
}

// SHA256Hex provides a mock function for the type MockDigester
func (_mock *MockDigester) SHA256Hex(data []byte) string {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for SHA256Hex")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDigester_SHA256Hex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SHA256Hex'
type MockDigester_SHA256Hex_Call struct {
	*mock.Call
}

// SHA256Hex is a helper method to define mock.On call
//   - data []byte
func (_e *MockDigester_Expecter) SHA256Hex(data interface{}) *MockDigester_SHA256Hex_Call {
	return &MockDigester_SHA256Hex_Call{Call: _e.mock.On("SHA256Hex", data)}
}

func (_c *MockDigester_SHA256Hex_Call) Run(run func(data []byte)) *MockDigester_SHA256Hex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDigester_SHA256Hex_Call) Return(s string) *MockDigester_SHA256Hex_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDigester_SHA256Hex_Call) RunAndReturn(run func(data []byte) string) *MockDigester_SHA256Hex_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEncryptor creates a new instance of MockEncryptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncryptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncryptor {
	mock := &MockEncryptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEncryptor is an autogenerated mock type for the Encryptor type
type MockEncryptor struct {
	mock.Mock
}

type MockEncryptor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncryptor) EXPECT() *MockEncryptor_Expecter {
	return &MockEncryptor_Expecter{mock: &_m.Mock}
}

// Encrypt provides a mock function for the type MockEncryptor
func (_mock *MockEncryptor) Encrypt(plaintext []byte) ([]byte, error) {
	ret := _mock.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(plaintext)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(plaintext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(plaintext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncryptor_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockEncryptor_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plaintext []byte
func (_e *MockEncryptor_Expecter) Encrypt(plaintext interface{}) *MockEncryptor_Encrypt_Call {
	return &MockEncryptor_Encrypt_Call{Call: _e.mock.On("Encrypt", plaintext)}
}

func (_c *MockEncryptor_Encrypt_Call) Run(run func(plaintext []byte)) *MockEncryptor_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEncryptor_Encrypt_Call) Return(bytes []byte, err error) *MockEncryptor_Encrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockEncryptor_Encrypt_Call) RunAndReturn(run func(plaintext []byte) ([]byte, error)) *MockEncryptor_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRfidRepository creates a new instance of MockRfidRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRfidRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRfidRepository {
	mock := &MockRfidRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRfidRepository is an autogenerated mock type for the RfidRepository type
type MockRfidRepository struct {
	mock.Mock
}

type MockRfidRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRfidRepository) EXPECT() *MockRfidRepository_Expecter {
	return &MockRfidRepository_Expecter{mock: &_m.Mock}
}

// AssociateVisit provides a mock function for the type MockRfidRepository
func (_mock *MockRfidRepository) AssociateVisit(ctx context.Context, rfidID uint16, visitID uuid.UUID) error {
	ret := _mock.Called(ctx, rfidID, visitID)

	if len(ret) == 0 {
		panic("no return value specified for AssociateVisit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint16, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, rfidID, visitID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRfidRepository_AssociateVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssociateVisit'
type MockRfidRepository_AssociateVisit_Call struct {
	*mock.Call
}

// AssociateVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - rfidID uint16
//   - visitID uuid.UUID
func (_e *MockRfidRepository_Expecter) AssociateVisit(ctx interface{}, rfidID interface{}, visitID interface{}) *MockRfidRepository_AssociateVisit_Call {
	return &MockRfidRepository_AssociateVisit_Call{Call: _e.mock.On("AssociateVisit", ctx, rfidID, visitID)}
}

func (_c *MockRfidRepository_AssociateVisit_Call) Run(run func(ctx context.Context, rfidID uint16, visitID uuid.UUID)) *MockRfidRepository_AssociateVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRfidRepository_AssociateVisit_Call) Return(err error) *MockRfidRepository_AssociateVisit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRfidRepository_AssociateVisit_Call) RunAndReturn(run func(ctx context.Context, rfidID uint16, visitID uuid.UUID) error) *MockRfidRepository_AssociateVisit_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUID provides a mock function for the type MockRfidRepository
func (_mock *MockRfidRepository) FindByUID(ctx context.Context, uid []byte) (*entity.Rfid, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for FindByUID")
	}

	var r0 *entity.Rfid
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (*entity.Rfid, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) *entity.Rfid); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Rfid)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRfidRepository_FindByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUID'
type MockRfidRepository_FindByUID_Call struct {
	*mock.Call
}

// FindByUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid []byte
func (_e *MockRfidRepository_Expecter) FindByUID(ctx interface{}, uid interface{}) *MockRfidRepository_FindByUID_Call {
	return &MockRfidRepository_FindByUID_Call{Call: _e.mock.On("FindByUID", ctx, uid)}
}

func (_c *MockRfidRepository_FindByUID_Call) Run(run func(ctx context.Context, uid []byte)) *MockRfidRepository_FindByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRfidRepository_FindByUID_Call) Return(rfid *entity.Rfid, err error) *MockRfidRepository_FindByUID_Call {
	_c.Call.Return(rfid, err)
	return _c
}

func (_c *MockRfidRepository_FindByUID_Call) RunAndReturn(run func(ctx context.Context, uid []byte) (*entity.Rfid, error)) *MockRfidRepository_FindByUID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTxRunner creates a new instance of MockTxRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxRunner {
	mock := &MockTxRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxRunner is an autogenerated mock type for the TxRunner type
type MockTxRunner struct {
	mock.Mock
}

type MockTxRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxRunner) EXPECT() *MockTxRunner_Expecter {
	return &MockTxRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockTxRunner
func (_mock *MockTxRunner) Run(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockTxRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTxRunner_Expecter) Run(ctx interface{}, fn interface{}) *MockTxRunner_Run_Call {
	return &MockTxRunner_Run_Call{Call: _e.mock.On("Run", ctx, fn)}
}

func (_c *MockTxRunner_Run_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTxRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxRunner_Run_Call) Return(err error) *MockTxRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxRunner_Run_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTxRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVisitRepository creates a new instance of MockVisitRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVisitRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVisitRepository {
	mock := &MockVisitRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVisitRepository is an autogenerated mock type for the VisitRepository type
type MockVisitRepository struct {
	mock.Mock
}

type MockVisitRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVisitRepository) EXPECT() *MockVisitRepository_Expecter {
	return &MockVisitRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockVisitRepository
func (_mock *MockVisitRepository) Create(ctx context.Context, v *entity.Visit) error {
	ret := _mock.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Visit) error); ok {
		r0 = returnFunc(ctx, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVisitRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVisitRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - v *entity.Visit
func (_e *MockVisitRepository_Expecter) Create(ctx interface{}, v interface{}) *MockVisitRepository_Create_Call {
	return &MockVisitRepository_Create_Call{Call: _e.mock.On("Create", ctx, v)}
}

func (_c *MockVisitRepository_Create_Call) Run(run func(ctx context.Context, v *entity.Visit)) *MockVisitRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Visit
		if args[1] != nil {
			arg1 = args[1].(*entity.Visit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVisitRepository_Create_Call) Return(err error) *MockVisitRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVisitRepository_Create_Call) RunAndReturn(run func(ctx context.Context, v *entity.Visit) error) *MockVisitRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockVisitRepository
func (_mock *MockVisitRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Visit, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Visit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Visit, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Visit); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Visit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVisitRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockVisitRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVisitRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockVisitRepository_FindByID_Call {
	return &MockVisitRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockVisitRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVisitRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVisitRepository_FindByID_Call) Return(visit *entity.Visit, err error) *MockVisitRepository_FindByID_Call {
	_c.Call.Return(visit, err)
	return _c
}

func (_c *MockVisitRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Visit, error)) *MockVisitRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindLatestByVisitor provides a mock function for the type MockVisitRepository
func (_mock *MockVisitRepository) FindLatestByVisitor(ctx context.Context, visitorID uuid.UUID) (*entity.Visit, error) {
	ret := _mock.Called(ctx, visitorID)

	if len(ret) == 0 {
		panic("no return value specified for FindLatestByVisitor")
	}

	var r0 *entity.Visit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Visit, error)); ok {
		return returnFunc(ctx, visitorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Visit); ok {
		r0 = returnFunc(ctx, visitorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Visit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, visitorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVisitRepository_FindLatestByVisitor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLatestByVisitor'
type MockVisitRepository_FindLatestByVisitor_Call struct {
	*mock.Call
}

// FindLatestByVisitor is a helper method to define mock.On call
//   - ctx context.Context
//   - visitorID uuid.UUID
func (_e *MockVisitRepository_Expecter) FindLatestByVisitor(ctx interface{}, visitorID interface{}) *MockVisitRepository_FindLatestByVisitor_Call {
	return &MockVisitRepository_FindLatestByVisitor_Call{Call: _e.mock.On("FindLatestByVisitor", ctx, visitorID)}
}

func (_c *MockVisitRepository_FindLatestByVisitor_Call) Run(run func(ctx context.Context, visitorID uuid.UUID)) *MockVisitRepository_FindLatestByVisitor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVisitRepository_FindLatestByVisitor_Call) Return(visit *entity.Visit, err error) *MockVisitRepository_FindLatestByVisitor_Call {
	_c.Call.Return(visit, err)
	return _c
}

func (_c *MockVisitRepository_FindLatestByVisitor_Call) RunAndReturn(run func(ctx context.Context, visitorID uuid.UUID) (*entity.Visit, error)) *MockVisitRepository_FindLatestByVisitor_Call {
	_c.Call.Return(run)
	return _c
}

// ListByGate provides a mock function for the type MockVisitRepository
func (_mock *MockVisitRepository) ListByGate(ctx context.Context, gateID int16) ([]entity.Visit, error) {
	ret := _mock.Called(ctx, gateID)

	if len(ret) == 0 {
		panic("no return value specified for ListByGate")
	}

	var r0 []entity.Visit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) ([]entity.Visit, error)); ok {
		return returnFunc(ctx, gateID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) []entity.Visit); ok {
		r0 = returnFunc(ctx, gateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Visit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int16) error); ok {
		r1 = returnFunc(ctx, gateID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVisitRepository_ListByGate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByGate'
type MockVisitRepository_ListByGate_Call struct {
	*mock.Call
}

// ListByGate is a helper method to define mock.On call
//   - ctx context.Context
//   - gateID int16
func (_e *MockVisitRepository_Expecter) ListByGate(ctx interface{}, gateID interface{}) *MockVisitRepository_ListByGate_Call {
	return &MockVisitRepository_ListByGate_Call{Call: _e.mock.On("ListByGate", ctx, gateID)}
}

func (_c *MockVisitRepository_ListByGate_Call) Run(run func(ctx context.Context, gateID int16)) *MockVisitRepository_ListByGate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int16
		if args[1] != nil {
			arg1 = args[1].(int16)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVisitRepository_ListByGate_Call) Return(visits []entity.Visit, err error) *MockVisitRepository_ListByGate_Call {
	_c.Call.Return(visits, err)
	return _c
}

func (_c *MockVisitRepository_ListByGate_Call) RunAndReturn(run func(ctx context.Context, gateID int16) ([]entity.Visit, error)) *MockVisitRepository_ListByGate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateState provides a mock function for the type MockVisitRepository
func (_mock *MockVisitRepository) UpdateState(ctx context.Context, id uuid.UUID, pos entity.CurrentPosition, checkoutAt *time.Time, checkoutGateID *int16) (*entity.Visit, error) {
	ret := _mock.Called(ctx, id, pos, checkoutAt, checkoutGateID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateState")
	}

	var r0 *entity.Visit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.CurrentPosition, *time.Time, *int16) (*entity.Visit, error)); ok {
		return returnFunc(ctx, id, pos, checkoutAt, checkoutGateID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.CurrentPosition, *time.Time, *int16) *entity.Visit); ok {
		r0 = returnFunc(ctx, id, pos, checkoutAt, checkoutGateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Visit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.CurrentPosition, *time.Time, *int16) error); ok {
		r1 = returnFunc(ctx, id, pos, checkoutAt, checkoutGateID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVisitRepository_UpdateState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateState'
type MockVisitRepository_UpdateState_Call struct {
	*mock.Call
}

// UpdateState is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - pos entity.CurrentPosition
//   - checkoutAt *time.Time
//   - checkoutGateID *int16
func (_e *MockVisitRepository_Expecter) UpdateState(ctx interface{}, id interface{}, pos interface{}, checkoutAt interface{}, checkoutGateID interface{}) *MockVisitRepository_UpdateState_Call {
	return &MockVisitRepository_UpdateState_Call{Call: _e.mock.On("UpdateState", ctx, id, pos, checkoutAt, checkoutGateID)}
}

func (_c *MockVisitRepository_UpdateState_Call) Run(run func(ctx context.Context, id uuid.UUID, pos entity.CurrentPosition, checkoutAt *time.Time, checkoutGateID *int16)) *MockVisitRepository_UpdateState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 entity.CurrentPosition
		if args[2] != nil {
			arg2 = args[2].(entity.CurrentPosition)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		var arg4 *int16
		if args[4] != nil {
			arg4 = args[4].(*int16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockVisitRepository_UpdateState_Call) Return(visit *entity.Visit, err error) *MockVisitRepository_UpdateState_Call {
	_c.Call.Return(visit, err)
	return _c
}

func (_c *MockVisitRepository_UpdateState_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, pos entity.CurrentPosition, checkoutAt *time.Time, checkoutGateID *int16) (*entity.Visit, error)) *MockVisitRepository_UpdateState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVisitorRepository creates a new instance of MockVisitorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVisitorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVisitorRepository {
	mock := &MockVisitorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVisitorRepository is an autogenerated mock type for the VisitorRepository type
type MockVisitorRepository struct {
	mock.Mock
}

type MockVisitorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVisitorRepository) EXPECT() *MockVisitorRepository_Expecter {
	return &MockVisitorRepository_Expecter{mock: &_m.Mock}
}

// ClearBan provides a mock function for the type MockVisitorRepository
func (_mock *MockVisitorRepository) ClearBan(ctx context.Context, visitorID uuid.UUID) error {
	ret := _mock.Called(ctx, visitorID)

	if len(ret) == 0 {
		panic("no return value specified for ClearBan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, visitorID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVisitorRepository_ClearBan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearBan'
type MockVisitorRepository_ClearBan_Call struct {
	*mock.Call
}

// ClearBan is a helper method to define mock.On call
//   - ctx context.Context
//   - visitorID uuid.UUID
func (_e *MockVisitorRepository_Expecter) ClearBan(ctx interface{}, visitorID interface{}) *MockVisitorRepository_ClearBan_Call {
	return &MockVisitorRepository_ClearBan_Call{Call: _e.mock.On("ClearBan", ctx, visitorID)}
}

func (_c *MockVisitorRepository_ClearBan_Call) Run(run func(ctx context.Context, visitorID uuid.UUID)) *MockVisitorRepository_ClearBan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVisitorRepository_ClearBan_Call) Return(err error) *MockVisitorRepository_ClearBan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVisitorRepository_ClearBan_Call) RunAndReturn(run func(ctx context.Context, visitorID uuid.UUID) error) *MockVisitorRepository_ClearBan_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIdentityHash provides a mock function for the type MockVisitorRepository
func (_mock *MockVisitorRepository) FindByIdentityHash(ctx context.Context, identityHashHex string) (*entity.Visitor, error) {
	ret := _mock.Called(ctx, identityHashHex)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdentityHash")
	}

	var r0 *entity.Visitor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Visitor, error)); ok {
		return returnFunc(ctx, identityHashHex)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Visitor); ok {
		r0 = returnFunc(ctx, identityHashHex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Visitor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, identityHashHex)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVisitorRepository_FindByIdentityHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIdentityHash'
type MockVisitorRepository_FindByIdentityHash_Call struct {
	*mock.Call
}

// FindByIdentityHash is a helper method to define mock.On call
//   - ctx context.Context
//   - identityHashHex string
func (_e *MockVisitorRepository_Expecter) FindByIdentityHash(ctx interface{}, identityHashHex interface{}) *MockVisitorRepository_FindByIdentityHash_Call {
	return &MockVisitorRepository_FindByIdentityHash_Call{Call: _e.mock.On("FindByIdentityHash", ctx, identityHashHex)}
}

func (_c *MockVisitorRepository_FindByIdentityHash_Call) Run(run func(ctx context.Context, identityHashHex string)) *MockVisitorRepository_FindByIdentityHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVisitorRepository_FindByIdentityHash_Call) Return(visitor *entity.Visitor, err error) *MockVisitorRepository_FindByIdentityHash_Call {
	_c.Call.Return(visitor, err)
	return _c
}

func (_c *MockVisitorRepository_FindByIdentityHash_Call) RunAndReturn(run func(ctx context.Context, identityHashHex string) (*entity.Visitor, error)) *MockVisitorRepository_FindByIdentityHash_Call {
	_c.Call.Return(run)
	return _c
}

// MarkBanned provides a mock function for the type MockVisitorRepository
func (_mock *MockVisitorRepository) MarkBanned(ctx context.Context, visitorID uuid.UUID, reason string, bannedAt time.Time) error {
	ret := _mock.Called(ctx, visitorID, reason, bannedAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkBanned")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) error); ok {
		r0 = returnFunc(ctx, visitorID, reason, bannedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVisitorRepository_MarkBanned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkBanned'
type MockVisitorRepository_MarkBanned_Call struct {
	*mock.Call
}

// MarkBanned is a helper method to define mock.On call
//   - ctx context.Context
//   - visitorID uuid.UUID
//   - reason string
//   - bannedAt time.Time
func (_e *MockVisitorRepository_Expecter) MarkBanned(ctx interface{}, visitorID interface{}, reason interface{}, bannedAt interface{}) *MockVisitorRepository_MarkBanned_Call {
	return &MockVisitorRepository_MarkBanned_Call{Call: _e.mock.On("MarkBanned", ctx, visitorID, reason, bannedAt)}
}

func (_c *MockVisitorRepository_MarkBanned_Call) Run(run func(ctx context.Context, visitorID uuid.UUID, reason string, bannedAt time.Time)) *MockVisitorRepository_MarkBanned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVisitorRepository_MarkBanned_Call) Return(err error) *MockVisitorRepository_MarkBanned_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVisitorRepository_MarkBanned_Call) RunAndReturn(run func(ctx context.Context, visitorID uuid.UUID, reason string, bannedAt time.Time) error) *MockVisitorRepository_MarkBanned_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertByIdentityHash provides a mock function for the type MockVisitorRepository
func (_mock *MockVisitorRepository) UpsertByIdentityHash(ctx context.Context, identityHashHex string, fullname string) (*entity.Visitor, error) {
	ret := _mock.Called(ctx, identityHashHex, fullname)

	if len(ret) == 0 {
		panic("no return value specified for UpsertByIdentityHash")
	}

	var r0 *entity.Visitor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entity.Visitor, error)); ok {
		return returnFunc(ctx, identityHashHex, fullname)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entity.Visitor); ok {
		r0 = returnFunc(ctx, identityHashHex, fullname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Visitor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, identityHashHex, fullname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVisitorRepository_UpsertByIdentityHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertByIdentityHash'
type MockVisitorRepository_UpsertByIdentityHash_Call struct {
	*mock.Call
}

// UpsertByIdentityHash is a helper method to define mock.On call
//   - ctx context.Context
//   - identityHashHex string
//   - fullname string
func (_e *MockVisitorRepository_Expecter) UpsertByIdentityHash(ctx interface{}, identityHashHex interface{}, fullname interface{}) *MockVisitorRepository_UpsertByIdentityHash_Call {
	return &MockVisitorRepository_UpsertByIdentityHash_Call{Call: _e.mock.On("UpsertByIdentityHash", ctx, identityHashHex, fullname)}
}

func (_c *MockVisitorRepository_UpsertByIdentityHash_Call) Run(run func(ctx context.Context, identityHashHex string, fullname string)) *MockVisitorRepository_UpsertByIdentityHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVisitorRepository_UpsertByIdentityHash_Call) Return(visitor *entity.Visitor, err error) *MockVisitorRepository_UpsertByIdentityHash_Call {
	_c.Call.Return(visitor, err)
	return _c
}

func (_c *MockVisitorRepository_UpsertByIdentityHash_Call) RunAndReturn(run func(ctx context.Context, identityHashHex string, fullname string) (*entity.Visitor, error)) *MockVisitorRepository_UpsertByIdentityHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCheckoutVisitUsecase creates a new instance of MockCheckoutVisitUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckoutVisitUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckoutVisitUsecase {
	mock := &MockCheckoutVisitUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheckoutVisitUsecase is an autogenerated mock type for the CheckoutVisitUsecase type
type MockCheckoutVisitUsecase struct {
	mock.Mock
}

type MockCheckoutVisitUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckoutVisitUsecase) EXPECT() *MockCheckoutVisitUsecase_Expecter {
	return &MockCheckoutVisitUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCheckoutVisitUsecase
func (_mock *MockCheckoutVisitUsecase) Execute(ctx context.Context, in CheckoutVisitInput) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CheckoutVisitInput) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCheckoutVisitUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCheckoutVisitUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in CheckoutVisitInput
func (_e *MockCheckoutVisitUsecase_Expecter) Execute(ctx interface{}, in interface{}) *MockCheckoutVisitUsecase_Execute_Call {
	return &MockCheckoutVisitUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockCheckoutVisitUsecase_Execute_Call) Run(run func(ctx context.Context, in CheckoutVisitInput)) *MockCheckoutVisitUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CheckoutVisitInput
		if args[1] != nil {
			arg1 = args[1].(CheckoutVisitInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCheckoutVisitUsecase_Execute_Call) Return(err error) *MockCheckoutVisitUsecase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCheckoutVisitUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, in CheckoutVisitInput) error) *MockCheckoutVisitUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateVisitUsecase creates a new instance of MockCreateVisitUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateVisitUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateVisitUsecase {
	mock := &MockCreateVisitUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateVisitUsecase is an autogenerated mock type for the CreateVisitUsecase type
type MockCreateVisitUsecase struct {
	mock.Mock
}

type MockCreateVisitUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateVisitUsecase) EXPECT() *MockCreateVisitUsecase_Expecter {
	return &MockCreateVisitUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCreateVisitUsecase
func (_mock *MockCreateVisitUsecase) Execute(ctx context.Context, in CreateVisitInput) (*CreateVisitOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *CreateVisitOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateVisitInput) (*CreateVisitOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateVisitInput) *CreateVisitOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateVisitOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateVisitInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateVisitUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateVisitUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in CreateVisitInput
func (_e *MockCreateVisitUsecase_Expecter) Execute(ctx interface{}, in interface{}) *MockCreateVisitUsecase_Execute_Call {
	return &MockCreateVisitUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockCreateVisitUsecase_Execute_Call) Run(run func(ctx context.Context, in CreateVisitInput)) *MockCreateVisitUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateVisitInput
		if args[1] != nil {
			arg1 = args[1].(CreateVisitInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateVisitUsecase_Execute_Call) Return(createVisitOutput *CreateVisitOutput, err error) *MockCreateVisitUsecase_Execute_Call {
	_c.Call.Return(createVisitOutput, err)
	return _c
}

func (_c *MockCreateVisitUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, in CreateVisitInput) (*CreateVisitOutput, error)) *MockCreateVisitUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetVisitHistoryUsecase creates a new instance of MockGetVisitHistoryUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetVisitHistoryUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetVisitHistoryUsecase {
	mock := &MockGetVisitHistoryUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetVisitHistoryUsecase is an autogenerated mock type for the GetVisitHistoryUsecase type
type MockGetVisitHistoryUsecase struct {
	mock.Mock
}

type MockGetVisitHistoryUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetVisitHistoryUsecase) EXPECT() *MockGetVisitHistoryUsecase_Expecter {
	return &MockGetVisitHistoryUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockGetVisitHistoryUsecase
func (_mock *MockGetVisitHistoryUsecase) Execute(ctx context.Context, gateID int16) ([]entity.Visit, error) {
	ret := _mock.Called(ctx, gateID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []entity.Visit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) ([]entity.Visit, error)); ok {
		return returnFunc(ctx, gateID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) []entity.Visit); ok {
		r0 = returnFunc(ctx, gateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Visit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int16) error); ok {
		r1 = returnFunc(ctx, gateID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetVisitHistoryUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetVisitHistoryUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - gateID int16
func (_e *MockGetVisitHistoryUsecase_Expecter) Execute(ctx interface{}, gateID interface{}) *MockGetVisitHistoryUsecase_Execute_Call {
	return &MockGetVisitHistoryUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, gateID)}
}

func (_c *MockGetVisitHistoryUsecase_Execute_Call) Run(run func(ctx context.Context, gateID int16)) *MockGetVisitHistoryUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int16
		if args[1] != nil {
			arg1 = args[1].(int16)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetVisitHistoryUsecase_Execute_Call) Return(visits []entity.Visit, err error) *MockGetVisitHistoryUsecase_Execute_Call {
	_c.Call.Return(visits, err)
	return _c
}

func (_c *MockGetVisitHistoryUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, gateID int16) ([]entity.Visit, error)) *MockGetVisitHistoryUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetVisitorStatusUsecase creates a new instance of MockGetVisitorStatusUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetVisitorStatusUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetVisitorStatusUsecase {
	mock := &MockGetVisitorStatusUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetVisitorStatusUsecase is an autogenerated mock type for the GetVisitorStatusUsecase type
type MockGetVisitorStatusUsecase struct {
	mock.Mock
}

type MockGetVisitorStatusUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetVisitorStatusUsecase) EXPECT() *MockGetVisitorStatusUsecase_Expecter {
	return &MockGetVisitorStatusUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockGetVisitorStatusUsecase
func (_mock *MockGetVisitorStatusUsecase) Execute(ctx context.Context, identityNumber string) (*GetVisitorStatusOutput, error) {
	ret := _mock.Called(ctx, identityNumber)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *GetVisitorStatusOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*GetVisitorStatusOutput, error)); ok {
		return returnFunc(ctx, identityNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *GetVisitorStatusOutput); ok {
		r0 = returnFunc(ctx, identityNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetVisitorStatusOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, identityNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetVisitorStatusUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetVisitorStatusUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - identityNumber string
func (_e *MockGetVisitorStatusUsecase_Expecter) Execute(ctx interface{}, identityNumber interface{}) *MockGetVisitorStatusUsecase_Execute_Call {
	return &MockGetVisitorStatusUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, identityNumber)}
}

func (_c *MockGetVisitorStatusUsecase_Execute_Call) Run(run func(ctx context.Context, identityNumber string)) *MockGetVisitorStatusUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetVisitorStatusUsecase_Execute_Call) Return(getVisitorStatusOutput *GetVisitorStatusOutput, err error) *MockGetVisitorStatusUsecase_Execute_Call {
	_c.Call.Return(getVisitorStatusOutput, err)
	return _c
}

func (_c *MockGetVisitorStatusUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, identityNumber string) (*GetVisitorStatusOutput, error)) *MockGetVisitorStatusUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransitEnterVisitUsecase creates a new instance of MockTransitEnterVisitUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransitEnterVisitUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransitEnterVisitUsecase {
	mock := &MockTransitEnterVisitUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransitEnterVisitUsecase is an autogenerated mock type for the TransitEnterVisitUsecase type
type MockTransitEnterVisitUsecase struct {
	mock.Mock
}

type MockTransitEnterVisitUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransitEnterVisitUsecase) EXPECT() *MockTransitEnterVisitUsecase_Expecter {
	return &MockTransitEnterVisitUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockTransitEnterVisitUsecase
func (_mock *MockTransitEnterVisitUsecase) Execute(ctx context.Context, in TransitEnterVisitInput) (*TransitEnterVisitOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *TransitEnterVisitOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, TransitEnterVisitInput) (*TransitEnterVisitOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, TransitEnterVisitInput) *TransitEnterVisitOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TransitEnterVisitOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, TransitEnterVisitInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitEnterVisitUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockTransitEnterVisitUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in TransitEnterVisitInput
func (_e *MockTransitEnterVisitUsecase_Expecter) Execute(ctx interface{}, in interface{}) *MockTransitEnterVisitUsecase_Execute_Call {
	return &MockTransitEnterVisitUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockTransitEnterVisitUsecase_Execute_Call) Run(run func(ctx context.Context, in TransitEnterVisitInput)) *MockTransitEnterVisitUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 TransitEnterVisitInput
		if args[1] != nil {
			arg1 = args[1].(TransitEnterVisitInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransitEnterVisitUsecase_Execute_Call) Return(transitEnterVisitOutput *TransitEnterVisitOutput, err error) *MockTransitEnterVisitUsecase_Execute_Call {
	_c.Call.Return(transitEnterVisitOutput, err)
	return _c
}

func (_c *MockTransitEnterVisitUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, in TransitEnterVisitInput) (*TransitEnterVisitOutput, error)) *MockTransitEnterVisitUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransitVisitUsecase creates a new instance of MockTransitVisitUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransitVisitUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransitVisitUsecase {
	mock := &MockTransitVisitUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransitVisitUsecase is an autogenerated mock type for the TransitVisitUsecase type
type MockTransitVisitUsecase struct {
	mock.Mock
}

type MockTransitVisitUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransitVisitUsecase) EXPECT() *MockTransitVisitUsecase_Expecter {
	return &MockTransitVisitUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockTransitVisitUsecase
func (_mock *MockTransitVisitUsecase) Execute(ctx context.Context, in TransitVisitInput) (*TransitVisitOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *TransitVisitOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, TransitVisitInput) (*TransitVisitOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, TransitVisitInput) *TransitVisitOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TransitVisitOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, TransitVisitInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitVisitUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockTransitVisitUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in TransitVisitInput
func (_e *MockTransitVisitUsecase_Expecter) Execute(ctx interface{}, in interface{}) *MockTransitVisitUsecase_Execute_Call {
	return &MockTransitVisitUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockTransitVisitUsecase_Execute_Call) Run(run func(ctx context.Context, in TransitVisitInput)) *MockTransitVisitUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 TransitVisitInput
		if args[1] != nil {
			arg1 = args[1].(TransitVisitInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransitVisitUsecase_Execute_Call) Return(transitVisitOutput *TransitVisitOutput, err error) *MockTransitVisitUsecase_Execute_Call {
	_c.Call.Return(transitVisitOutput, err)
	return _c
}

func (_c *MockTransitVisitUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, in TransitVisitInput) (*TransitVisitOutput, error)) *MockTransitVisitUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
