// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"

	"github.com/hansenhalim/dgb/api/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRfidRepository creates a new instance of MockRfidRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRfidRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRfidRepository {
	mock := &MockRfidRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRfidRepository is an autogenerated mock type for the RfidRepository type
type MockRfidRepository struct {
	mock.Mock
}

type MockRfidRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRfidRepository) EXPECT() *MockRfidRepository_Expecter {
	return &MockRfidRepository_Expecter{mock: &_m.Mock}
}

// FindByUID provides a mock function for the type MockRfidRepository
func (_mock *MockRfidRepository) FindByUID(ctx context.Context, uid []byte) (*entity.Rfid, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for FindByUID")
	}

	var r0 *entity.Rfid
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (*entity.Rfid, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) *entity.Rfid); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Rfid)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRfidRepository_FindByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUID'
type MockRfidRepository_FindByUID_Call struct {
	*mock.Call
}

// FindByUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid []byte
func (_e *MockRfidRepository_Expecter) FindByUID(ctx interface{}, uid interface{}) *MockRfidRepository_FindByUID_Call {
	return &MockRfidRepository_FindByUID_Call{Call: _e.mock.On("FindByUID", ctx, uid)}
}

func (_c *MockRfidRepository_FindByUID_Call) Run(run func(ctx context.Context, uid []byte)) *MockRfidRepository_FindByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRfidRepository_FindByUID_Call) Return(rfid *entity.Rfid, err error) *MockRfidRepository_FindByUID_Call {
	_c.Call.Return(rfid, err)
	return _c
}

func (_c *MockRfidRepository_FindByUID_Call) RunAndReturn(run func(ctx context.Context, uid []byte) (*entity.Rfid, error)) *MockRfidRepository_FindByUID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetRfidKeyUsecase creates a new instance of MockGetRfidKeyUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetRfidKeyUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetRfidKeyUsecase {
	mock := &MockGetRfidKeyUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetRfidKeyUsecase is an autogenerated mock type for the GetRfidKeyUsecase type
type MockGetRfidKeyUsecase struct {
	mock.Mock
}

type MockGetRfidKeyUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetRfidKeyUsecase) EXPECT() *MockGetRfidKeyUsecase_Expecter {
	return &MockGetRfidKeyUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockGetRfidKeyUsecase
func (_mock *MockGetRfidKeyUsecase) Execute(ctx context.Context, uid []byte) (*GetRfidKeyOutput, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *GetRfidKeyOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (*GetRfidKeyOutput, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) *GetRfidKeyOutput); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetRfidKeyOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetRfidKeyUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetRfidKeyUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - uid []byte
func (_e *MockGetRfidKeyUsecase_Expecter) Execute(ctx interface{}, uid interface{}) *MockGetRfidKeyUsecase_Execute_Call {
	return &MockGetRfidKeyUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, uid)}
}

func (_c *MockGetRfidKeyUsecase_Execute_Call) Run(run func(ctx context.Context, uid []byte)) *MockGetRfidKeyUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetRfidKeyUsecase_Execute_Call) Return(getRfidKeyOutput *GetRfidKeyOutput, err error) *MockGetRfidKeyUsecase_Execute_Call {
	_c.Call.Return(getRfidKeyOutput, err)
	return _c
}

func (_c *MockGetRfidKeyUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, uid []byte) (*GetRfidKeyOutput, error)) *MockGetRfidKeyUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
