// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"

	"github.com/hansenhalim/dgb/api/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGateAvailabilityChecker creates a new instance of MockGateAvailabilityChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGateAvailabilityChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGateAvailabilityChecker {
	mock := &MockGateAvailabilityChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGateAvailabilityChecker is an autogenerated mock type for the GateAvailabilityChecker type
type MockGateAvailabilityChecker struct {
	mock.Mock
}

type MockGateAvailabilityChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGateAvailabilityChecker) EXPECT() *MockGateAvailabilityChecker_Expecter {
	return &MockGateAvailabilityChecker_Expecter{mock: &_m.Mock}
}

// IsAvailable provides a mock function for the type MockGateAvailabilityChecker
func (_mock *MockGateAvailabilityChecker) IsAvailable(gateID int16) bool {
	ret := _mock.Called(gateID)

	if len(ret) == 0 {
		panic("no return value specified for IsAvailable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int16) bool); ok {
		r0 = returnFunc(gateID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGateAvailabilityChecker_IsAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAvailable'
type MockGateAvailabilityChecker_IsAvailable_Call struct {
	*mock.Call
}

// IsAvailable is a helper method to define mock.On call
//   - gateID int16
func (_e *MockGateAvailabilityChecker_Expecter) IsAvailable(gateID interface{}) *MockGateAvailabilityChecker_IsAvailable_Call {
	return &MockGateAvailabilityChecker_IsAvailable_Call{Call: _e.mock.On("IsAvailable", gateID)}
}

func (_c *MockGateAvailabilityChecker_IsAvailable_Call) Run(run func(gateID int16)) *MockGateAvailabilityChecker_IsAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int16
		if args[0] != nil {
			arg0 = args[0].(int16)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGateAvailabilityChecker_IsAvailable_Call) Return(b bool) *MockGateAvailabilityChecker_IsAvailable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGateAvailabilityChecker_IsAvailable_Call) RunAndReturn(run func(gateID int16) bool) *MockGateAvailabilityChecker_IsAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGateRepository creates a new instance of MockGateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGateRepository {
	mock := &MockGateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGateRepository is an autogenerated mock type for the GateRepository type
type MockGateRepository struct {
	mock.Mock
}

type MockGateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGateRepository) EXPECT() *MockGateRepository_Expecter {
	return &MockGateRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type MockGateRepository
func (_mock *MockGateRepository) FindByID(ctx context.Context, id int16) (*entity.Gate, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Gate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) (*entity.Gate, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) *entity.Gate); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Gate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int16) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGateRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockGateRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int16
func (_e *MockGateRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockGateRepository_FindByID_Call {
	return &MockGateRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockGateRepository_FindByID_Call) Run(run func(ctx context.Context, id int16)) *MockGateRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int16
		if args[1] != nil {
			arg1 = args[1].(int16)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGateRepository_FindByID_Call) Return(gate *entity.Gate, err error) *MockGateRepository_FindByID_Call {
	_c.Call.Return(gate, err)
	return _c
}

func (_c *MockGateRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int16) (*entity.Gate, error)) *MockGateRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function for the type MockGateRepository
func (_mock *MockGateRepository) ListAll(ctx context.Context) ([]entity.Gate, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []entity.Gate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.Gate, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.Gate); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Gate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGateRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockGateRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGateRepository_Expecter) ListAll(ctx interface{}) *MockGateRepository_ListAll_Call {
	return &MockGateRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockGateRepository_ListAll_Call) Run(run func(ctx context.Context)) *MockGateRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGateRepository_ListAll_Call) Return(gates []entity.Gate, err error) *MockGateRepository_ListAll_Call {
	_c.Call.Return(gates, err)
	return _c
}

func (_c *MockGateRepository_ListAll_Call) RunAndReturn(run func(ctx context.Context) ([]entity.Gate, error)) *MockGateRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListGatesUsecase creates a new instance of MockListGatesUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListGatesUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListGatesUsecase {
	mock := &MockListGatesUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListGatesUsecase is an autogenerated mock type for the ListGatesUsecase type
type MockListGatesUsecase struct {
	mock.Mock
}

type MockListGatesUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListGatesUsecase) EXPECT() *MockListGatesUsecase_Expecter {
	return &MockListGatesUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockListGatesUsecase
func (_mock *MockListGatesUsecase) Execute(ctx context.Context) (*ListGatesOutput, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *ListGatesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*ListGatesOutput, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *ListGatesOutput); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ListGatesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListGatesUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockListGatesUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockListGatesUsecase_Expecter) Execute(ctx interface{}) *MockListGatesUsecase_Execute_Call {
	return &MockListGatesUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockListGatesUsecase_Execute_Call) Run(run func(ctx context.Context)) *MockListGatesUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockListGatesUsecase_Execute_Call) Return(listGatesOutput *ListGatesOutput, err error) *MockListGatesUsecase_Execute_Call {
	_c.Call.Return(listGatesOutput, err)
	return _c
}

func (_c *MockListGatesUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context) (*ListGatesOutput, error)) *MockListGatesUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
