// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/hansenhalim/dgb/api/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClock creates a new instance of MockClock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClock {
	mock := &MockClock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClock is an autogenerated mock type for the Clock type
type MockClock struct {
	mock.Mock
}

type MockClock_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClock) EXPECT() *MockClock_Expecter {
	return &MockClock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type MockClock
func (_mock *MockClock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockClock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockClock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockClock_Expecter) Now() *MockClock_Now_Call {
	return &MockClock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockClock_Now_Call) Run(run func()) *MockClock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClock_Now_Call) Return(time1 time.Time) *MockClock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockClock_Now_Call) RunAndReturn(run func() time.Time) *MockClock_Now_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGateRepository creates a new instance of MockGateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGateRepository {
	mock := &MockGateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGateRepository is an autogenerated mock type for the GateRepository type
type MockGateRepository struct {
	mock.Mock
}

type MockGateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGateRepository) EXPECT() *MockGateRepository_Expecter {
	return &MockGateRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type MockGateRepository
func (_mock *MockGateRepository) FindByID(ctx context.Context, id int16) (*entity.Gate, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Gate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) (*entity.Gate, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) *entity.Gate); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Gate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int16) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGateRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockGateRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int16
func (_e *MockGateRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockGateRepository_FindByID_Call {
	return &MockGateRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockGateRepository_FindByID_Call) Run(run func(ctx context.Context, id int16)) *MockGateRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int16
		if args[1] != nil {
			arg1 = args[1].(int16)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGateRepository_FindByID_Call) Return(gate *entity.Gate, err error) *MockGateRepository_FindByID_Call {
	_c.Call.Return(gate, err)
	return _c
}

func (_c *MockGateRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int16) (*entity.Gate, error)) *MockGateRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransferRequestRepository creates a new instance of MockTransferRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransferRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransferRequestRepository {
	mock := &MockTransferRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransferRequestRepository is an autogenerated mock type for the TransferRequestRepository type
type MockTransferRequestRepository struct {
	mock.Mock
}

type MockTransferRequestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransferRequestRepository) EXPECT() *MockTransferRequestRepository_Expecter {
	return &MockTransferRequestRepository_Expecter{mock: &_m.Mock}
}

// Confirm provides a mock function for the type MockTransferRequestRepository
func (_mock *MockTransferRequestRepository) Confirm(ctx context.Context, id int64, recipientStaffID uuid.UUID, respondedAt time.Time) error {
	ret := _mock.Called(ctx, id, recipientStaffID, respondedAt)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, id, recipientStaffID, respondedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransferRequestRepository_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type MockTransferRequestRepository_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - recipientStaffID uuid.UUID
//   - respondedAt time.Time
func (_e *MockTransferRequestRepository_Expecter) Confirm(ctx interface{}, id interface{}, recipientStaffID interface{}, respondedAt interface{}) *MockTransferRequestRepository_Confirm_Call {
	return &MockTransferRequestRepository_Confirm_Call{Call: _e.mock.On("Confirm", ctx, id, recipientStaffID, respondedAt)}
}

func (_c *MockTransferRequestRepository_Confirm_Call) Run(run func(ctx context.Context, id int64, recipientStaffID uuid.UUID, respondedAt time.Time)) *MockTransferRequestRepository_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransferRequestRepository_Confirm_Call) Return(err error) *MockTransferRequestRepository_Confirm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransferRequestRepository_Confirm_Call) RunAndReturn(run func(ctx context.Context, id int64, recipientStaffID uuid.UUID, respondedAt time.Time) error) *MockTransferRequestRepository_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockTransferRequestRepository
func (_mock *MockTransferRequestRepository) Create(ctx context.Context, t *entity.TransferRequest) error {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TransferRequest) error); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransferRequestRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransferRequestRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t *entity.TransferRequest
func (_e *MockTransferRequestRepository_Expecter) Create(ctx interface{}, t interface{}) *MockTransferRequestRepository_Create_Call {
	return &MockTransferRequestRepository_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *MockTransferRequestRepository_Create_Call) Run(run func(ctx context.Context, t *entity.TransferRequest)) *MockTransferRequestRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.TransferRequest
		if args[1] != nil {
			arg1 = args[1].(*entity.TransferRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransferRequestRepository_Create_Call) Return(err error) *MockTransferRequestRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransferRequestRepository_Create_Call) RunAndReturn(run func(ctx context.Context, t *entity.TransferRequest) error) *MockTransferRequestRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPendingByGateID provides a mock function for the type MockTransferRequestRepository
func (_mock *MockTransferRequestRepository) FindAllPendingByGateID(ctx context.Context, gateID int16) ([]*entity.TransferRequest, error) {
	ret := _mock.Called(ctx, gateID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPendingByGateID")
	}

	var r0 []*entity.TransferRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) ([]*entity.TransferRequest, error)); ok {
		return returnFunc(ctx, gateID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) []*entity.TransferRequest); ok {
		r0 = returnFunc(ctx, gateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TransferRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int16) error); ok {
		r1 = returnFunc(ctx, gateID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransferRequestRepository_FindAllPendingByGateID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPendingByGateID'
type MockTransferRequestRepository_FindAllPendingByGateID_Call struct {
	*mock.Call
}

// FindAllPendingByGateID is a helper method to define mock.On call
//   - ctx context.Context
//   - gateID int16
func (_e *MockTransferRequestRepository_Expecter) FindAllPendingByGateID(ctx interface{}, gateID interface{}) *MockTransferRequestRepository_FindAllPendingByGateID_Call {
	return &MockTransferRequestRepository_FindAllPendingByGateID_Call{Call: _e.mock.On("FindAllPendingByGateID", ctx, gateID)}
}

func (_c *MockTransferRequestRepository_FindAllPendingByGateID_Call) Run(run func(ctx context.Context, gateID int16)) *MockTransferRequestRepository_FindAllPendingByGateID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int16
		if args[1] != nil {
			arg1 = args[1].(int16)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransferRequestRepository_FindAllPendingByGateID_Call) Return(transferRequests []*entity.TransferRequest, err error) *MockTransferRequestRepository_FindAllPendingByGateID_Call {
	_c.Call.Return(transferRequests, err)
	return _c
}

func (_c *MockTransferRequestRepository_FindAllPendingByGateID_Call) RunAndReturn(run func(ctx context.Context, gateID int16) ([]*entity.TransferRequest, error)) *MockTransferRequestRepository_FindAllPendingByGateID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockTransferRequestRepository
func (_mock *MockTransferRequestRepository) FindByID(ctx context.Context, id int64) (*entity.TransferRequest, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.TransferRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*entity.TransferRequest, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *entity.TransferRequest); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TransferRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransferRequestRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTransferRequestRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTransferRequestRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockTransferRequestRepository_FindByID_Call {
	return &MockTransferRequestRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTransferRequestRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockTransferRequestRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransferRequestRepository_FindByID_Call) Return(transferRequest *entity.TransferRequest, err error) *MockTransferRequestRepository_FindByID_Call {
	_c.Call.Return(transferRequest, err)
	return _c
}

func (_c *MockTransferRequestRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*entity.TransferRequest, error)) *MockTransferRequestRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Reject provides a mock function for the type MockTransferRequestRepository
func (_mock *MockTransferRequestRepository) Reject(ctx context.Context, id int64, recipientStaffID uuid.UUID, respondedAt time.Time) error {
	ret := _mock.Called(ctx, id, recipientStaffID, respondedAt)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, id, recipientStaffID, respondedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransferRequestRepository_Reject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reject'
type MockTransferRequestRepository_Reject_Call struct {
	*mock.Call
}

// Reject is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - recipientStaffID uuid.UUID
//   - respondedAt time.Time
func (_e *MockTransferRequestRepository_Expecter) Reject(ctx interface{}, id interface{}, recipientStaffID interface{}, respondedAt interface{}) *MockTransferRequestRepository_Reject_Call {
	return &MockTransferRequestRepository_Reject_Call{Call: _e.mock.On("Reject", ctx, id, recipientStaffID, respondedAt)}
}

func (_c *MockTransferRequestRepository_Reject_Call) Run(run func(ctx context.Context, id int64, recipientStaffID uuid.UUID, respondedAt time.Time)) *MockTransferRequestRepository_Reject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransferRequestRepository_Reject_Call) Return(err error) *MockTransferRequestRepository_Reject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransferRequestRepository_Reject_Call) RunAndReturn(run func(ctx context.Context, id int64, recipientStaffID uuid.UUID, respondedAt time.Time) error) *MockTransferRequestRepository_Reject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCheckTransferRequestUsecase creates a new instance of MockCheckTransferRequestUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckTransferRequestUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckTransferRequestUsecase {
	mock := &MockCheckTransferRequestUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheckTransferRequestUsecase is an autogenerated mock type for the CheckTransferRequestUsecase type
type MockCheckTransferRequestUsecase struct {
	mock.Mock
}

type MockCheckTransferRequestUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckTransferRequestUsecase) EXPECT() *MockCheckTransferRequestUsecase_Expecter {
	return &MockCheckTransferRequestUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCheckTransferRequestUsecase
func (_mock *MockCheckTransferRequestUsecase) Execute(ctx context.Context, gateID int16) ([]*entity.TransferRequest, error) {
	ret := _mock.Called(ctx, gateID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*entity.TransferRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) ([]*entity.TransferRequest, error)); ok {
		return returnFunc(ctx, gateID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int16) []*entity.TransferRequest); ok {
		r0 = returnFunc(ctx, gateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TransferRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int16) error); ok {
		r1 = returnFunc(ctx, gateID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCheckTransferRequestUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCheckTransferRequestUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - gateID int16
func (_e *MockCheckTransferRequestUsecase_Expecter) Execute(ctx interface{}, gateID interface{}) *MockCheckTransferRequestUsecase_Execute_Call {
	return &MockCheckTransferRequestUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, gateID)}
}

func (_c *MockCheckTransferRequestUsecase_Execute_Call) Run(run func(ctx context.Context, gateID int16)) *MockCheckTransferRequestUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int16
		if args[1] != nil {
			arg1 = args[1].(int16)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCheckTransferRequestUsecase_Execute_Call) Return(transferRequests []*entity.TransferRequest, err error) *MockCheckTransferRequestUsecase_Execute_Call {
	_c.Call.Return(transferRequests, err)
	return _c
}

func (_c *MockCheckTransferRequestUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, gateID int16) ([]*entity.TransferRequest, error)) *MockCheckTransferRequestUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateTransferRequestUsecase creates a new instance of MockCreateTransferRequestUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateTransferRequestUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateTransferRequestUsecase {
	mock := &MockCreateTransferRequestUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateTransferRequestUsecase is an autogenerated mock type for the CreateTransferRequestUsecase type
type MockCreateTransferRequestUsecase struct {
	mock.Mock
}

type MockCreateTransferRequestUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateTransferRequestUsecase) EXPECT() *MockCreateTransferRequestUsecase_Expecter {
	return &MockCreateTransferRequestUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCreateTransferRequestUsecase
func (_mock *MockCreateTransferRequestUsecase) Execute(ctx context.Context, in CreateTransferRequestInput) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateTransferRequestInput) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreateTransferRequestUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateTransferRequestUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in CreateTransferRequestInput
func (_e *MockCreateTransferRequestUsecase_Expecter) Execute(ctx interface{}, in interface{}) *MockCreateTransferRequestUsecase_Execute_Call {
	return &MockCreateTransferRequestUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockCreateTransferRequestUsecase_Execute_Call) Run(run func(ctx context.Context, in CreateTransferRequestInput)) *MockCreateTransferRequestUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateTransferRequestInput
		if args[1] != nil {
			arg1 = args[1].(CreateTransferRequestInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateTransferRequestUsecase_Execute_Call) Return(err error) *MockCreateTransferRequestUsecase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreateTransferRequestUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, in CreateTransferRequestInput) error) *MockCreateTransferRequestUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRespondTransferRequestUsecase creates a new instance of MockRespondTransferRequestUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRespondTransferRequestUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRespondTransferRequestUsecase {
	mock := &MockRespondTransferRequestUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRespondTransferRequestUsecase is an autogenerated mock type for the RespondTransferRequestUsecase type
type MockRespondTransferRequestUsecase struct {
	mock.Mock
}

type MockRespondTransferRequestUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRespondTransferRequestUsecase) EXPECT() *MockRespondTransferRequestUsecase_Expecter {
	return &MockRespondTransferRequestUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockRespondTransferRequestUsecase
func (_mock *MockRespondTransferRequestUsecase) Execute(ctx context.Context, in RespondTransferRequestInput) (*RespondTransferRequestOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *RespondTransferRequestOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, RespondTransferRequestInput) (*RespondTransferRequestOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, RespondTransferRequestInput) *RespondTransferRequestOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RespondTransferRequestOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, RespondTransferRequestInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRespondTransferRequestUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockRespondTransferRequestUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in RespondTransferRequestInput
func (_e *MockRespondTransferRequestUsecase_Expecter) Execute(ctx interface{}, in interface{}) *MockRespondTransferRequestUsecase_Execute_Call {
	return &MockRespondTransferRequestUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockRespondTransferRequestUsecase_Execute_Call) Run(run func(ctx context.Context, in RespondTransferRequestInput)) *MockRespondTransferRequestUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 RespondTransferRequestInput
		if args[1] != nil {
			arg1 = args[1].(RespondTransferRequestInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRespondTransferRequestUsecase_Execute_Call) Return(respondTransferRequestOutput *RespondTransferRequestOutput, err error) *MockRespondTransferRequestUsecase_Execute_Call {
	_c.Call.Return(respondTransferRequestOutput, err)
	return _c
}

func (_c *MockRespondTransferRequestUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, in RespondTransferRequestInput) (*RespondTransferRequestOutput, error)) *MockRespondTransferRequestUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
