// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"

	"github.com/hansenhalim/dgb/api/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDestinationRepository creates a new instance of MockDestinationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDestinationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDestinationRepository {
	mock := &MockDestinationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDestinationRepository is an autogenerated mock type for the DestinationRepository type
type MockDestinationRepository struct {
	mock.Mock
}

type MockDestinationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDestinationRepository) EXPECT() *MockDestinationRepository_Expecter {
	return &MockDestinationRepository_Expecter{mock: &_m.Mock}
}

// ListAll provides a mock function for the type MockDestinationRepository
func (_mock *MockDestinationRepository) ListAll(ctx context.Context) ([]entity.Destination, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []entity.Destination
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.Destination, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.Destination); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Destination)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDestinationRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockDestinationRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDestinationRepository_Expecter) ListAll(ctx interface{}) *MockDestinationRepository_ListAll_Call {
	return &MockDestinationRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockDestinationRepository_ListAll_Call) Run(run func(ctx context.Context)) *MockDestinationRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDestinationRepository_ListAll_Call) Return(destinations []entity.Destination, err error) *MockDestinationRepository_ListAll_Call {
	_c.Call.Return(destinations, err)
	return _c
}

func (_c *MockDestinationRepository_ListAll_Call) RunAndReturn(run func(ctx context.Context) ([]entity.Destination, error)) *MockDestinationRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListDestinationsUsecase creates a new instance of MockListDestinationsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListDestinationsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListDestinationsUsecase {
	mock := &MockListDestinationsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListDestinationsUsecase is an autogenerated mock type for the ListDestinationsUsecase type
type MockListDestinationsUsecase struct {
	mock.Mock
}

type MockListDestinationsUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListDestinationsUsecase) EXPECT() *MockListDestinationsUsecase_Expecter {
	return &MockListDestinationsUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockListDestinationsUsecase
func (_mock *MockListDestinationsUsecase) Execute(ctx context.Context) ([]entity.Destination, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []entity.Destination
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.Destination, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.Destination); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Destination)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListDestinationsUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockListDestinationsUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockListDestinationsUsecase_Expecter) Execute(ctx interface{}) *MockListDestinationsUsecase_Execute_Call {
	return &MockListDestinationsUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockListDestinationsUsecase_Execute_Call) Run(run func(ctx context.Context)) *MockListDestinationsUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockListDestinationsUsecase_Execute_Call) Return(destinations []entity.Destination, err error) *MockListDestinationsUsecase_Execute_Call {
	_c.Call.Return(destinations, err)
	return _c
}

func (_c *MockListDestinationsUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context) ([]entity.Destination, error)) *MockListDestinationsUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
