// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"
	"time"

	"github.com/hansenhalim/dgb/api/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClock creates a new instance of MockClock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClock {
	mock := &MockClock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClock is an autogenerated mock type for the Clock type
type MockClock struct {
	mock.Mock
}

type MockClock_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClock) EXPECT() *MockClock_Expecter {
	return &MockClock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type MockClock
func (_mock *MockClock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockClock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockClock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockClock_Expecter) Now() *MockClock_Now_Call {
	return &MockClock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockClock_Now_Call) Run(run func()) *MockClock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClock_Now_Call) Return(time1 time.Time) *MockClock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockClock_Now_Call) RunAndReturn(run func() time.Time) *MockClock_Now_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDigester creates a new instance of MockDigester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDigester(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDigester {
	mock := &MockDigester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDigester is an autogenerated mock type for the Digester type
type MockDigester struct {
	mock.Mock
}

type MockDigester_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDigester) EXPECT() *MockDigester_Expecter {
	return &MockDigester_Expecter{mock: &_m.Mock}
}

// SHA256Hex provides a mock function for the type MockDigester
func (_mock *MockDigester) SHA256Hex(data []byte) string {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for SHA256Hex")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDigester_SHA256Hex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SHA256Hex'
type MockDigester_SHA256Hex_Call struct {
	*mock.Call
}

// SHA256Hex is a helper method to define mock.On call
//   - data []byte
func (_e *MockDigester_Expecter) SHA256Hex(data interface{}) *MockDigester_SHA256Hex_Call {
	return &MockDigester_SHA256Hex_Call{Call: _e.mock.On("SHA256Hex", data)}
}

func (_c *MockDigester_SHA256Hex_Call) Run(run func(data []byte)) *MockDigester_SHA256Hex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDigester_SHA256Hex_Call) Return(s string) *MockDigester_SHA256Hex_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDigester_SHA256Hex_Call) RunAndReturn(run func(data []byte) string) *MockDigester_SHA256Hex_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHasher creates a new instance of MockHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasher {
	mock := &MockHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHasher is an autogenerated mock type for the Hasher type
type MockHasher struct {
	mock.Mock
}

type MockHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasher) EXPECT() *MockHasher_Expecter {
	return &MockHasher_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockHasher
func (_mock *MockHasher) Verify(hashed string, plaintext string) (bool, error) {
	ret := _mock.Called(hashed, plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(hashed, plaintext)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(hashed, plaintext)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(hashed, plaintext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHasher_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockHasher_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - hashed string
//   - plaintext string
func (_e *MockHasher_Expecter) Verify(hashed interface{}, plaintext interface{}) *MockHasher_Verify_Call {
	return &MockHasher_Verify_Call{Call: _e.mock.On("Verify", hashed, plaintext)}
}

func (_c *MockHasher_Verify_Call) Run(run func(hashed string, plaintext string)) *MockHasher_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHasher_Verify_Call) Return(b bool, err error) *MockHasher_Verify_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockHasher_Verify_Call) RunAndReturn(run func(hashed string, plaintext string) (bool, error)) *MockHasher_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRfidRepository creates a new instance of MockRfidRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRfidRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRfidRepository {
	mock := &MockRfidRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRfidRepository is an autogenerated mock type for the RfidRepository type
type MockRfidRepository struct {
	mock.Mock
}

type MockRfidRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRfidRepository) EXPECT() *MockRfidRepository_Expecter {
	return &MockRfidRepository_Expecter{mock: &_m.Mock}
}

// FindGuardByUID provides a mock function for the type MockRfidRepository
func (_mock *MockRfidRepository) FindGuardByUID(ctx context.Context, uid []byte) (*entity.Rfid, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for FindGuardByUID")
	}

	var r0 *entity.Rfid
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (*entity.Rfid, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) *entity.Rfid); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Rfid)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRfidRepository_FindGuardByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindGuardByUID'
type MockRfidRepository_FindGuardByUID_Call struct {
	*mock.Call
}

// FindGuardByUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid []byte
func (_e *MockRfidRepository_Expecter) FindGuardByUID(ctx interface{}, uid interface{}) *MockRfidRepository_FindGuardByUID_Call {
	return &MockRfidRepository_FindGuardByUID_Call{Call: _e.mock.On("FindGuardByUID", ctx, uid)}
}

func (_c *MockRfidRepository_FindGuardByUID_Call) Run(run func(ctx context.Context, uid []byte)) *MockRfidRepository_FindGuardByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRfidRepository_FindGuardByUID_Call) Return(rfid *entity.Rfid, err error) *MockRfidRepository_FindGuardByUID_Call {
	_c.Call.Return(rfid, err)
	return _c
}

func (_c *MockRfidRepository_FindGuardByUID_Call) RunAndReturn(run func(ctx context.Context, uid []byte) (*entity.Rfid, error)) *MockRfidRepository_FindGuardByUID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenIssuer creates a new instance of MockTokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenIssuer {
	mock := &MockTokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenIssuer is an autogenerated mock type for the TokenIssuer type
type MockTokenIssuer struct {
	mock.Mock
}

type MockTokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenIssuer) EXPECT() *MockTokenIssuer_Expecter {
	return &MockTokenIssuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function for the type MockTokenIssuer
func (_mock *MockTokenIssuer) Issue(subject string, expiresAt time.Time) (string, error) {
	ret := _mock.Called(subject, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, time.Time) (string, error)); ok {
		return returnFunc(subject, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(string, time.Time) string); ok {
		r0 = returnFunc(subject, expiresAt)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = returnFunc(subject, expiresAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockTokenIssuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - subject string
//   - expiresAt time.Time
func (_e *MockTokenIssuer_Expecter) Issue(subject interface{}, expiresAt interface{}) *MockTokenIssuer_Issue_Call {
	return &MockTokenIssuer_Issue_Call{Call: _e.mock.On("Issue", subject, expiresAt)}
}

func (_c *MockTokenIssuer_Issue_Call) Run(run func(subject string, expiresAt time.Time)) *MockTokenIssuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenIssuer_Issue_Call) Return(s string, err error) *MockTokenIssuer_Issue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenIssuer_Issue_Call) RunAndReturn(run func(subject string, expiresAt time.Time) (string, error)) *MockTokenIssuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerifyPinUsecase creates a new instance of MockVerifyPinUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifyPinUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifyPinUsecase {
	mock := &MockVerifyPinUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerifyPinUsecase is an autogenerated mock type for the VerifyPinUsecase type
type MockVerifyPinUsecase struct {
	mock.Mock
}

type MockVerifyPinUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifyPinUsecase) EXPECT() *MockVerifyPinUsecase_Expecter {
	return &MockVerifyPinUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockVerifyPinUsecase
func (_mock *MockVerifyPinUsecase) Execute(ctx context.Context, in VerifyPinInput) (*VerifyPinOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *VerifyPinOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, VerifyPinInput) (*VerifyPinOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, VerifyPinInput) *VerifyPinOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VerifyPinOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, VerifyPinInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifyPinUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockVerifyPinUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in VerifyPinInput
func (_e *MockVerifyPinUsecase_Expecter) Execute(ctx interface{}, in interface{}) *MockVerifyPinUsecase_Execute_Call {
	return &MockVerifyPinUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockVerifyPinUsecase_Execute_Call) Run(run func(ctx context.Context, in VerifyPinInput)) *MockVerifyPinUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 VerifyPinInput
		if args[1] != nil {
			arg1 = args[1].(VerifyPinInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVerifyPinUsecase_Execute_Call) Return(verifyPinOutput *VerifyPinOutput, err error) *MockVerifyPinUsecase_Execute_Call {
	_c.Call.Return(verifyPinOutput, err)
	return _c
}

func (_c *MockVerifyPinUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, in VerifyPinInput) (*VerifyPinOutput, error)) *MockVerifyPinUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerifySecretUsecase creates a new instance of MockVerifySecretUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifySecretUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifySecretUsecase {
	mock := &MockVerifySecretUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerifySecretUsecase is an autogenerated mock type for the VerifySecretUsecase type
type MockVerifySecretUsecase struct {
	mock.Mock
}

type MockVerifySecretUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifySecretUsecase) EXPECT() *MockVerifySecretUsecase_Expecter {
	return &MockVerifySecretUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockVerifySecretUsecase
func (_mock *MockVerifySecretUsecase) Execute(ctx context.Context, in VerifySecretInput) (*VerifySecretOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *VerifySecretOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, VerifySecretInput) (*VerifySecretOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, VerifySecretInput) *VerifySecretOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VerifySecretOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, VerifySecretInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifySecretUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockVerifySecretUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in VerifySecretInput
func (_e *MockVerifySecretUsecase_Expecter) Execute(ctx interface{}, in interface{}) *MockVerifySecretUsecase_Execute_Call {
	return &MockVerifySecretUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockVerifySecretUsecase_Execute_Call) Run(run func(ctx context.Context, in VerifySecretInput)) *MockVerifySecretUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 VerifySecretInput
		if args[1] != nil {
			arg1 = args[1].(VerifySecretInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVerifySecretUsecase_Execute_Call) Return(verifySecretOutput *VerifySecretOutput, err error) *MockVerifySecretUsecase_Execute_Call {
	_c.Call.Return(verifySecretOutput, err)
	return _c
}

func (_c *MockVerifySecretUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, in VerifySecretInput) (*VerifySecretOutput, error)) *MockVerifySecretUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
